### ISSUE TITLE
How do you manage your notifications? 

### ISSUE THREAD

**Issue by jcsrb** [toddmotto/ama#2]
I assume lots of emails, github  and twitter notifications

**Comment by toddmotto** [comment]
I really don't manage them or have a strategy for being efficient.

Email: I have my Gmail open (all three main domains/accounts in different Chrome profiles) all day and have done for about 5 years now. I mark emails as "Unread" and stack them in my important list for ones I need time responding to, these often take a few days.

Twitter: Chrome tab is always open and notifications on my phone are always on - fastest / best way to contact me for sure :)

GitHub: To be fair my personal OS GitHub stuff is actually mildly quiet (thankfully - I'd be rather overwhelmed otherwise). I do however work with a tonne of different companies through [voux.io](http://voux.io) so am subscribed to a bunch of different organisations - these can be erratic to make sure I delete ones I don't need to be involved in :dancer:
