### ISSUE TITLE
How do you balance your work/life time?

### ISSUE THREAD

**Issue by amejiarosario** [toddmotto/ama#31]
I mean javascript technologies are in constant change. It's very time consuming to be on top of them. Furthermore, work from 9 to 5, write posts, go to gym and maintain a relationship... What things have work for you and what haven't? (The more detailed the examples, the better)

**Comment by toddmotto** [comment]
Hey Adrian! So, I'm always working on something, or planning new things to work on in my spare time. I work at Telerik during the day, and then after work I work on new ideas, toying with new languages and go for a run when I choose to. I'm building a tonne of courses at the moment [over here](https://courses.toddmotto.com) which are taking up my weekends and evenings right now. Thankfully my girlfriend is super awesome and is actually helping me plan them and ensure things are super clear from a conceptual basis etc. So that's really great to have. I don't usually dedicate time and have free days off at the moment, however in the past (and after my courses are out) I'll be taking a few nights off a week to just chill out as that time is essential :) what things in particular are you doing that asked this question? :)

**Comment by amejiarosario** [comment]
Hey man, those AngularJS courses are awesome! Congrats!

I'm just getting started to teach as well through my [blog](http://adrianmejia.com/) and [book](https://github.com/amejiarosario/meanshop/blob/master/README.md). It takes a ton of time, so I was just wondering how other people with more experience make time for it. I guess the only way is sacrificing free time and nights until the projects take off. Once they generate enough revenue, one could dedicate full time on those projects... That's your plan with your online training courses?

**Comment by toddmotto** [comment]
Thanks! :D nearly there with the first course release Monday/Tuesday.

I know, it's certainly worth investing in though - I do love it. Certainly could go full-time, though I love having a day job and being able to invest time in the community like I do with Telerik - I'm not sure I'd want to go full-time course making as I always like to shape my skills on new projects and I love that (even in previous jobs).

Then I can reach people in two ways: community and teaching, I've always loved teaching regardless of where I've been working though!
