### ISSUE TITLE
Reading habits

### ISSUE THREAD

**Issue by benoror** [toddmotto/ama#4]
Considering our field (IT) is evolving exponentially, I am very curious on how other people have their daily doses of information to stay relevant and updated.
- What kind of information sources do you consume on a regular basis (Books, Magazines, Twitter, HN, Blog Feeds, Podcasts, ...)?
- What off-topics are you interested in (IT-related, besides the work-related specifics)?
- What tools do you use regularly (E-Reader, Tweetdeck, Medium, Feedkly, Pocket Casts)?
- Do you allocate some time of your day for consuming information, or you just do it on the fly?
- Do you have an specific routine/process for information consumption?

**Comment by toddmotto** [comment]
Funnily enough, I write a tonne of articles, but absolutely loathe reading.

I read as little as possible (articles/blogs). I actually prefer looking at source code as the internal workings of things interest me way more. I usually scan GitHub source code on various projects (Angular/Angular 2 or anything else I stumble across and want to dive deeper) to lookup new information.

I don't read books, ever. Or buy magazines. For me, Twitter is the go-to medium for seeing latest evolvements in the areas I am interested in, which is why I actually don't follow that many people (I keep the list concise and focused on where I can pickup new information without "searching for it" myself).

Apps, people tell me all the time "you must install this app that does that same thing as your other app but looks cool". I'm very simple in terms of apps, I use standard apps; twitter, apple mail and the like for everything. I don't even have many apps on my phone either.

Time allocation is something I've been thinking of, however my daily schedules are erratic so I soak up new things mainly by reading things like source code etc as mentioned above :)

**Comment by benoror** [comment]
Cool, thanks for answering!
