### ISSUE TITLE
Advice for an aspiring tech blogger?

### ISSUE THREAD

**Issue by thebestmensch** [toddmotto/ama#48]
Hey Todd,

I've wanted to begin contributing to the tech community for a while now, whether it be blogging, speaking, or another medium. I've struggled trying to find content I think is 'good enough' to write about, and I end up not posting my work. Any advice?

**Comment by toddmotto** [comment]
Hey James! This is a great question that sadly often gets overlooked.

First off, I'd highly recommend setting up your own blog, perhaps on Jekyll like my site is, which is essentially free hosting from GitHub pages, you can fork the [repo here](https://github.com/toddmotto/toddmotto.github.io) and take a look around. You'll need to install Jekyll locally on your Mac/PC, build out some articles and then simply push to git when ready. I highly recommend this approach over something like publishing on Medium/whatever. Creating your own source of resources in a centralised place has many benefits:
- Traffic to your own blog, builds up your name in the long term
- Building up your own knowledge base (having your own content/tutorials in your own words is far easier to look back on than, for example, someone else's blog article on the same topic)

With regards to "what" to blog about, this is always a fun one. There are certain cycles you certainly go through, typically ending in these kind of thoughts:
- Oh wait, someone's already blogged about this, forget it
- This is too basic/easy
- No one will care about this post
- I suck at writing
- My English sucks (usually hear this from non-native-English speakers)

To all of the above, always just go for it. In my experience, there are thousands more people searching for "How to do a for loop in JavaScript" than "How to subscribe to an RxJS foo.bar() call" for example. If you think it's basic, that's because you've mastered it. But there are hundreds of thousands of developers that haven't. Be that guy for them when they google something. There are also countless developers upcoming and new to the industry, each month new people start off in the web community, so more resources are better for them to get started.

I wouldn't advise jumping straight into blogging writing some crazy in-depth post. Establish a goal for your blog, for example mine's mainly AngularJS, JavaScript and some sprinklings of React and HTML5 APIs. I figure if you've learned something cool, advanced, new, blog it. 

Biggest piece of advice: Just because you know something, doesn't mean everyone else does.

Share what you are passionate about, and that'll come across in your writing :)

I hope that helps somewhat! 💃

**Comment by thebestmensch** [comment]
Wonderful response, thanks!

**Comment by toddmotto** [comment]
Anytime :)
